name: Deployment

on:
  push:
    branches: [main, ci*]
  workflow_dispatch:

jobs:
  run:
    env:
      CI: true
      NODE_ENV: production
      MONGO_URI: ${{ secrets.MONGO_URI }}
      HOME_URI: ${{ secrets.HOME_URI }}
      API_URI: ${{ secrets.API_URI }}
      HOME_PORT: ${{ secrets.HOME_PORT }}
      API_PORT: ${{ secrets.API_PORT }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pm2 delete svbot-web || true
      - run: pm2 start npm --name "svbot-web" -- start
